miduner_server:
    build: .
    dockerfile: ./docker/Dockerfile
    working_dir: /var/www/html
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx_log:/var/log/php-fpm.log
      - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf

    links:
      - mysql
mysql:
    image: mysql:5.6
    container_name: sangtg_mysql
    ports:
      - "3309:3306"
    volumes:
      - ./docker/mysql:var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
